---
account_login_bottom: ''
add_go_to_top: 0
custom_help_url: 'http://www.redmine.org/guide'
disabled_modules:
external_urls: 1
global_footer: ''
global_sidebar: ''
wiki_pdf_header: ''
wiki_pdf_remove_title: 0
wiki_pdf_remove_attachments: 0
global_wiki_footer: ''
global_wiki_header: ''
global_wiki_sidebar: ''
issue_autowatch_involved: 1
issue_auto_assign_role: ''
issue_auto_assign_status: ''
issue_auto_assign: 0
legacy_smiley_support: 0
new_ticket_message: "Don't forget to define acceptance criteria!"
overview_bottom: ''
overview_right: ''
overview_top: ''
project_overview_content: 'Go to admin area and define a nice wiki text here as a fixed skeletal for all projects.'
remove_help: 0
remove_mypage: 0
remove_news: 0
